name: Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'package/**'
      - 'resources/**'
      - '*.releng'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'package/**'
      - 'resources/**'
      - '*.releng'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache downloads
        uses: actions/cache@v4
        id: cache-releng-tool
        with:
          path: |
            cache
            dl
          key: releng-tool

      - name: Prepare releng-tool
        run: pip install releng-tool

      - name: Needed Perl modules
        run: |
          cpan Locale::Maketext::Simple

      - name: Prepare Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      # Remove WSL Bash from the system, as it causes trouble with
      # a openssl build
      - name: Remove WSL Bash
        run: |
          takeown /F "C:\Windows\System32\bash.exe"
          icacls "C:\Windows\System32\bash.exe" /grant administrators:F
          Remove-Item C:\Windows\System32\bash.exe

      - name: Build release
        run: releng-tool
